---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages
- type: directory
  path: pages
  label: Pages
  create: all
  match: "**/*"
- type: heading
  label: Blog
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: heading
  label: Projects
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - project
- type: heading
  label: Bookshelf
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: preview
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
