import type { Metadata } from "next";
import "../styles/main.scss";
import { bodyFont } from "@/fonts";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Alert from "@/components/Alert";

export const metadata: Metadata = {
  title: {
    default: "Traek Wells",
    template: "%s | UX Designer & Front-End Developer",
  },
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={bodyFont.className}>
      <head>
        <link rel="icon" href="favicon.png" sizes="any" />
        <script
          defer
          data-domain="traekwells.com"
          src="https://plausible.io/js/script.js"
        ></script>
      </head>
      <body>
        <Alert>
          <p className="text-center">
            ⚠️ Currently under maintenance. You've been warned.
          </p>
        </Alert>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
