---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Project Title
- type: textarea
  name: summary
  label: Project Summary
- name: featured
  type: boolean
  label: Featured?
- name: featuredImage
  type: file
  config:
    maxSize: 64
  label: Featured Image
- name: previewImage
  type: file
  config:
    maxSize: 64
  label: Preview Image
- type: text
  name: linkToProject
  label: Link To Project
- type: text
  name: linkToCode
  label: Link To Code
- type: text
  name: technology
  label: Technology
