---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Project Title
- type: textarea
  name: summary
  label: Project Summary
- type: file
  name: previewImage
  label: Preview Image
- name: featuredImage
  type: file
  config:
    maxSize: 64
  label: Featured Image
- name: featured
  type: boolean
  label: Featured?
- type: text
  name: linkToProject
  label: Link To Project
- type: text
  name: linkToCode
  label: Link To Code
- type: text
  name: technology
  label: Technology
- name: images
  type: field_group_list
  fields:
  - name: preview_image
    type: file
    config:
      maxSize: 64
    label: Preview Image
    description: This is the image that shows up in the project feed.
  - name: featured_image
    type: file
    config:
      maxSize: 64
    label: Featured Image
    description: This is the image that shows up at the top of the project page.
  config:
    min: 
    max: 
    labelField: 
  label: Images
